use std::panic::{AssertUnwindSafe, catch_unwind};

use rsgdll_lua::{FromLua, Lua, LuaError, StackFrame, UserDataType};

use crate::{BoxError, Callback, ReturnWriter, install_dispatcher, register_callback, trampoline};

/// Callback descriptor generated by [`rsgdll_macros::function`].
#[doc(hidden)]
#[derive(Clone, Copy)]
pub struct Function {
    context: &'static str,
    callback: Callback,
}

impl Function {
    #[doc(hidden)]
    #[must_use]
    pub const fn new(context: &'static str, callback: Callback) -> Self {
        Self { context, callback }
    }

    /// Pushes this generated function through the generic C++ trampoline.
    ///
    /// # Safety
    ///
    /// Caller must ensure upvalue/closure pushes cannot raise a Lua error or
    /// longjmp.
    pub unsafe fn push(&self, frame: &mut StackFrame<'_, '_>) -> Result<(), BoxError> {
        let callback_id = register_callback(self.context, self.callback)?;
        // SAFETY: caller accepts both upvalue and closure push obligations.
        unsafe {
            frame.push(f64::from(callback_id.get()))?;
            frame.push_c_closure(trampoline(), 1)?;
        }
        Ok(())
    }

    /// Installs this generated function in a typed userdata metatable.
    ///
    /// # Safety
    ///
    /// Caller must ensure metatable, string, closure, and table mutations cannot
    /// raise a Lua error or longjmp.
    pub unsafe fn install_method<'guard, 'lua, T: 'static>(
        &self,
        frame: &mut StackFrame<'guard, 'lua>,
        userdata: &UserDataType<'lua, T>,
        name: &str,
    ) -> Result<(), BoxError> {
        // SAFETY: caller accepts every stack-mutating operation.
        unsafe {
            userdata.push_metatable(frame)?;
            frame.push(name)?;
            self.push(frame)?;
            frame.raw_set(-3)?;
        }
        frame.pop(1)?;
        Ok(())
    }

    unsafe fn push_with_type(
        &self,
        frame: &mut StackFrame<'_, '_>,
        lua_type: u8,
    ) -> Result<(), BoxError> {
        let callback_id = register_callback(self.context, self.callback)?;
        // SAFETY: caller accepts both upvalue and closure push obligations.
        unsafe {
            frame.push(f64::from(callback_id.get()))?;
            frame.push(f64::from(lua_type))?;
            frame.push_c_closure(trampoline(), 2)?;
        }
        Ok(())
    }
}

/// Installs the typed Rust destructor as a userdata `__gc` metamethod.
///
/// # Safety
///
/// Caller must ensure metatable, string, closure, and table mutations cannot
/// raise a Lua error or longjmp.
pub unsafe fn install_userdata_gc<'guard, 'lua, T: 'static>(
    frame: &mut StackFrame<'guard, 'lua>,
    userdata: &UserDataType<'lua, T>,
) -> Result<(), BoxError> {
    let function = Function::new("rsgdll userdata __gc", userdata_gc::<T>);
    // SAFETY: caller accepts every stack-mutating operation.
    unsafe {
        userdata.push_metatable(frame)?;
        frame.push("__gc")?;
        function.push_with_type(frame, userdata.type_id())?;
        frame.raw_set(-3)?;
    }
    frame.pop(1)?;
    Ok(())
}

fn userdata_gc<T: 'static>(
    frame: &mut StackFrame<'_, '_>,
    _: &mut ReturnWriter<'_>,
) -> Result<(), BoxError> {
    let type_index = Lua::upvalue_index(2)?;
    let raw_type = f64::from_lua(frame.lua(), type_index)?;
    if !raw_type.is_finite()
        || raw_type.fract() != 0.0
        || !(0.0..=f64::from(u8::MAX)).contains(&raw_type)
    {
        return Err(Box::new(LuaError::UserDataTypeOutOfRange));
    }
    // SAFETY: `install_userdata_gc::<T>` captured this type ID from the exact
    // `UserDataType<T>` used to install this callback.
    unsafe { UserDataType::<T>::finalize_registered(frame, 1, raw_type as u8)? };
    Ok(())
}

/// One function registration shared with the C++ module-opening firewall.
#[doc(hidden)]
#[repr(C)]
pub struct RawRegistration {
    pub name: *const u8,
    pub name_length: u32,
    pub callback_id: u32,
}

/// Builds the crate-named global table exported by a Garry's Mod binary module.
pub struct ModuleBuilder<'registration> {
    registrations: &'registration mut [RawRegistration],
    count: usize,
    failed: bool,
}

impl ModuleBuilder<'_> {
    /// Registers one generated Rust function under `name`.
    pub fn function(&mut self, name: &'static str, function: Function) -> &mut Self {
        if self.failed {
            return self;
        }
        let Some(registration) = self.registrations.get_mut(self.count) else {
            self.failed = true;
            return self;
        };
        let Ok(name_length) = u32::try_from(name.len()) else {
            self.failed = true;
            return self;
        };
        let Ok(callback_id) = register_callback(function.context, function.callback) else {
            self.failed = true;
            return self;
        };
        *registration = RawRegistration {
            name: name.as_ptr(),
            name_length,
            callback_id: callback_id.get(),
        };
        self.count += 1;
        self
    }
}

/// Runs non-Lua module registration and writes POD descriptors for C++.
///
/// # Safety
///
/// `registrations` must reference `capacity` initialized writable entries.
/// Every output pointer must be writable and remain exclusively borrowed for
/// this call.
#[doc(hidden)]
pub unsafe fn initialize_module(
    registrations: *mut RawRegistration,
    capacity: u32,
    output_count: *mut u32,
    output_name: *mut *const u8,
    output_name_length: *mut u32,
    module_path: &'static str,
    initializer: fn(&mut ModuleBuilder<'_>),
) -> u8 {
    if registrations.is_null()
        || output_count.is_null()
        || output_name.is_null()
        || output_name_length.is_null()
    {
        return 0;
    }
    // SAFETY: [Category 3 — dangling pointers] Caller guarantees every output
    // pointer is live, writable, and exclusively borrowed for this call.
    unsafe {
        output_count.write(0);
        output_name.write(std::ptr::null());
        output_name_length.write(0);
    }
    let module_name = crate_name(module_path);
    let Ok(module_name_length) = u32::try_from(module_name.len()) else {
        return 0;
    };
    let Ok(capacity) = usize::try_from(capacity) else {
        return 0;
    };
    // SAFETY: caller guarantees this exact initialized writable range.
    let registrations = unsafe { std::slice::from_raw_parts_mut(registrations, capacity) };
    install_dispatcher();
    let mut builder = ModuleBuilder {
        registrations,
        count: 0,
        failed: false,
    };
    if catch_unwind(AssertUnwindSafe(|| initializer(&mut builder))).is_err() || builder.failed {
        return 0;
    }
    let Ok(count) = u32::try_from(builder.count) else {
        return 0;
    };
    // SAFETY: [Category 3 — dangling pointers] Caller guarantees every output
    // pointer remains live, writable, and exclusive. `module_name` references
    // static `module_path!()` storage generated in the consumer crate.
    unsafe {
        output_count.write(count);
        output_name.write(module_name.as_ptr());
        output_name_length.write(module_name_length);
    }
    1
}

const _: () = assert!(std::mem::size_of::<RawRegistration>() == 16);

fn crate_name(module_path: &str) -> &str {
    module_path
        .split_once("::")
        .map_or(module_path, |(crate_name, _)| crate_name)
}

#[cfg(test)]
mod tests {
    use super::crate_name;

    #[test]
    fn crate_name_is_the_first_module_path_segment() {
        assert_eq!(crate_name("rsgdll_e2e::nested"), "rsgdll_e2e");
    }
}
