use std::panic::{AssertUnwindSafe, catch_unwind};

use crate::{Callback, install_dispatcher, register_callback};

/// Callback descriptor generated by [`rsgdll_macros::function`].
#[doc(hidden)]
#[derive(Clone, Copy)]
pub struct Function {
    context: &'static str,
    callback: Callback,
}

impl Function {
    #[doc(hidden)]
    #[must_use]
    pub const fn new(context: &'static str, callback: Callback) -> Self {
        Self { context, callback }
    }
}

/// One function registration shared with the C++ module-opening firewall.
#[doc(hidden)]
#[repr(C)]
pub struct RawRegistration {
    pub name: *const u8,
    pub name_length: u32,
    pub callback_id: u32,
}

/// Builds the Lua table returned by a Garry's Mod binary module.
pub struct ModuleBuilder<'registration> {
    registrations: &'registration mut [RawRegistration],
    count: usize,
    failed: bool,
}

impl ModuleBuilder<'_> {
    /// Registers one generated Rust function under `name`.
    pub fn function(&mut self, name: &'static str, function: Function) -> &mut Self {
        if self.failed {
            return self;
        }
        let Some(registration) = self.registrations.get_mut(self.count) else {
            self.failed = true;
            return self;
        };
        let Ok(name_length) = u32::try_from(name.len()) else {
            self.failed = true;
            return self;
        };
        let Ok(callback_id) = register_callback(function.context, function.callback) else {
            self.failed = true;
            return self;
        };
        *registration = RawRegistration {
            name: name.as_ptr(),
            name_length,
            callback_id: callback_id.get(),
        };
        self.count += 1;
        self
    }
}

/// Runs non-Lua module registration and writes POD descriptors for C++.
///
/// # Safety
///
/// `registrations` must reference `capacity` initialized writable entries and
/// `output_count` must be writable. Both pointers remain exclusively borrowed
/// for this call.
#[doc(hidden)]
pub unsafe fn initialize_module(
    registrations: *mut RawRegistration,
    capacity: u32,
    output_count: *mut u32,
    initializer: fn(&mut ModuleBuilder<'_>),
) -> u8 {
    if registrations.is_null() || output_count.is_null() {
        return 0;
    }
    // SAFETY: caller guarantees both output pointers are valid and exclusive.
    unsafe { output_count.write(0) };
    let Ok(capacity) = usize::try_from(capacity) else {
        return 0;
    };
    // SAFETY: caller guarantees this exact initialized writable range.
    let registrations = unsafe { std::slice::from_raw_parts_mut(registrations, capacity) };
    install_dispatcher();
    let mut builder = ModuleBuilder {
        registrations,
        count: 0,
        failed: false,
    };
    if catch_unwind(AssertUnwindSafe(|| initializer(&mut builder))).is_err() || builder.failed {
        return 0;
    }
    let Ok(count) = u32::try_from(builder.count) else {
        return 0;
    };
    // SAFETY: caller guarantees `output_count` remains writable for this call.
    unsafe { output_count.write(count) };
    1
}

const _: () = assert!(std::mem::size_of::<RawRegistration>() == 16);
