use std::ffi::c_char;
use std::panic::{AssertUnwindSafe, catch_unwind};

use rsgdll_bridge::ModuleRegistration as RawRegistration;
use rsgdll_lua::{StackFrame, UserDataType};

use crate::{
    BoxError, Callback, ErrorReport, PanicReport, install_dispatcher, register_callback, trampoline,
};

/// Callback descriptor generated by [`rsgdll_macros::function`].
#[doc(hidden)]
#[derive(Clone, Copy)]
pub struct Function {
    context: &'static str,
    callback: Callback,
}

impl Function {
    #[doc(hidden)]
    #[must_use]
    pub const fn new(context: &'static str, callback: Callback) -> Self {
        Self { context, callback }
    }

    /// Pushes this generated function through the generic C++ trampoline.
    pub fn push(&self, frame: &mut StackFrame<'_, '_>) -> Result<(), BoxError> {
        let callback_id = register_callback(self.context, self.callback)?;
        frame.push(f64::from(callback_id.get()))?;
        // SAFETY: generated callback uses the exact Lua C ABI and the Rust
        // dispatcher catches panics before returning across it.
        unsafe { rsgdll_lua::__private::push_c_closure(frame, trampoline(), 1)? };
        Ok(())
    }

    /// Installs this generated function in a typed userdata metatable.
    ///
    pub fn install_method<'guard, 'lua, T: 'static>(
        &self,
        frame: &mut StackFrame<'guard, 'lua>,
        userdata: &UserDataType<'lua, T>,
        name: &str,
    ) -> Result<(), BoxError> {
        userdata.push_metatable(frame)?;
        frame.push(name)?;
        self.push(frame)?;
        frame.raw_set(-3)?;
        frame.pop(1)?;
        Ok(())
    }
}

/// Builds the crate-named global table exported by a Garry's Mod binary module.
pub struct ModuleBuilder<'registration> {
    registrations: &'registration mut [RawRegistration],
    count: usize,
    failure: Option<String>,
}

impl ModuleBuilder<'_> {
    /// Registers one generated Rust function under `name`.
    pub fn function(&mut self, name: &'static str, function: Function) -> &mut Self {
        if self.failure.is_some() {
            return self;
        }
        let Some(registration) = self.registrations.get_mut(self.count) else {
            self.failure = Some(format!(
                "module registration capacity {} exceeded by export {name:?}",
                self.registrations.len()
            ));
            return self;
        };
        let Ok(name_length) = u32::try_from(name.len()) else {
            self.failure = Some(format!(
                "module export name {name:?} exceeds the ABI length limit"
            ));
            return self;
        };
        let callback_id = match register_callback(function.context, function.callback) {
            Ok(callback_id) => callback_id,
            Err(error) => {
                self.failure = Some(format!("register module export {name:?}: {error}"));
                return self;
            }
        };
        *registration = RawRegistration {
            name: name.as_ptr(),
            name_length,
            callback_id: callback_id.get(),
        };
        self.count += 1;
        self
    }
}

/// Runs non-Lua module registration and writes POD descriptors for C++.
///
/// # Safety
///
/// `registrations` must reference `capacity` initialized writable entries.
/// Every output pointer must be writable and remain exclusively borrowed for
/// this call.
#[doc(hidden)]
pub unsafe fn initialize_module(
    registrations: *mut RawRegistration,
    capacity: u32,
    output_count: *mut u32,
    output_metadata: (
        *mut *const u8,
        *mut u32,
        *mut *const rsgdll_bridge::AbiLayout,
    ),
    error: (*mut c_char, u32),
    module_path: &'static str,
    initializer: fn(&mut ModuleBuilder<'_>),
) -> u8 {
    let (output_name, output_name_length, output_abi_layout) = output_metadata;
    let (error_buffer, error_capacity) = error;
    if registrations.is_null()
        || output_count.is_null()
        || output_name.is_null()
        || output_name_length.is_null()
        || output_abi_layout.is_null()
    {
        return 0;
    }
    // SAFETY: [Category 3 — dangling pointers] Caller guarantees every output
    // pointer is live, writable, and exclusively borrowed for this call.
    unsafe {
        output_count.write(0);
        output_name.write(std::ptr::null());
        output_name_length.write(0);
        output_abi_layout.write(&rsgdll_bridge::ABI_LAYOUT);
    }
    let module_name = crate_name(module_path);
    let Ok(module_name_length) = u32::try_from(module_name.len()) else {
        return 0;
    };
    let Ok(capacity) = usize::try_from(capacity) else {
        return 0;
    };
    // SAFETY: caller guarantees this exact initialized writable range.
    let registrations = unsafe { std::slice::from_raw_parts_mut(registrations, capacity) };
    install_dispatcher();
    let mut builder = ModuleBuilder {
        registrations,
        count: 0,
        failure: None,
    };
    match catch_unwind(AssertUnwindSafe(|| initializer(&mut builder))) {
        Ok(()) => {}
        Err(payload) => {
            let wrote_report = catch_unwind(AssertUnwindSafe(|| {
                let report = PanicReport::capture(module_path, payload);
                crate::dispatcher::write_report(error_buffer, error_capacity, &report);
            }))
            .is_ok();
            if !wrote_report {
                crate::dispatcher::write_bytes(
                    error_buffer,
                    error_capacity,
                    b"panic while producing rsgdll module initialization report",
                );
            }
            return 0;
        }
    }
    if let Some(failure) = builder.failure {
        let report = ErrorReport::message(module_path, failure);
        crate::dispatcher::write_report(error_buffer, error_capacity, &report);
        return 0;
    }
    let Ok(count) = u32::try_from(builder.count) else {
        return 0;
    };
    // SAFETY: [Category 3 — dangling pointers] Caller guarantees every output
    // pointer remains live, writable, and exclusive. `module_name` references
    // static `module_path!()` storage generated in the consumer crate.
    unsafe {
        output_count.write(count);
        output_name.write(module_name.as_ptr());
        output_name_length.write(module_name_length);
    }
    1
}

fn crate_name(module_path: &str) -> &str {
    module_path
        .split_once("::")
        .map_or(module_path, |(crate_name, _)| crate_name)
}

#[cfg(test)]
mod tests {
    use super::{crate_name, initialize_module};
    use rsgdll_bridge::{ABI_LAYOUT, ModuleRegistration};

    #[test]
    fn crate_name_is_the_first_module_path_segment() {
        assert_eq!(crate_name("rsgdll_e2e::nested"), "rsgdll_e2e");
    }

    #[cfg(panic = "unwind")]
    #[test]
    fn initializer_panic_is_copied_for_cpp_reporting() {
        fn panic_initializer(_: &mut super::ModuleBuilder<'_>) {
            panic!("intentional initializer panic");
        }

        let mut registrations = std::array::from_fn::<_, 1, _>(|_| ModuleRegistration {
            name: std::ptr::null(),
            name_length: 0,
            callback_id: 0,
        });
        let mut count = 0;
        let mut name = std::ptr::null();
        let mut name_length = 0;
        let mut layout = std::ptr::null();
        let mut error = [0_i8; 256];

        // SAFETY: every pointer references writable storage for this call.
        let initialized = unsafe {
            initialize_module(
                registrations.as_mut_ptr(),
                registrations.len() as u32,
                &mut count,
                (&mut name, &mut name_length, &mut layout),
                (error.as_mut_ptr(), error.len() as u32),
                "test_module",
                panic_initializer,
            )
        };

        assert_eq!(initialized, 0);
        assert_eq!(layout, &ABI_LAYOUT);
        let length = error
            .iter()
            .position(|byte| *byte == 0)
            .unwrap_or(error.len());
        let message = String::from_utf8(error[..length].iter().map(|byte| *byte as u8).collect())
            .expect("report is UTF-8");
        assert!(message.contains("intentional initializer panic"));
    }
}
