[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
rsgdll-abi = { path = "crates/rsgdll-abi" }
rsgdll-bridge = { path = "crates/rsgdll-bridge" }
rsgdll-platform = { path = "crates/rsgdll-platform" }
rsgdll-lua = { path = "crates/rsgdll-lua" }
rsgdll-module = { path = "crates/rsgdll-module" }
rsgdll-runtime = { path = "crates/rsgdll-runtime" }
rsgdll-async = { path = "crates/rsgdll-async" }
rsgdll-macros = { path = "crates/rsgdll-macros" }
cc = "1"
