[package]
name = "rsgdll-lua"
version.workspace = true
edition.workspace = true

[features]
default = []
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
rsgdll-platform.workspace = true
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
rsgdll-abi.workspace = true
static_assertions = "1"
