[package]
name = "rsgdll-e2e"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
crash-test = []

[lib]
crate-type = ["cdylib"]

[dependencies]
rsgdll = { path = "../../crates/rsgdll", features = ["async", "backtrace", "engine", "serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"

[workspace]
