services:
  runner:
    container_name: ${RSGDLL_E2E_CONTAINER_NAME}
    restart: "no"
    entrypoint: ["/bin/bash", "/home/steam/rsgdll-entrypoint.sh"]
    ulimits:
      core:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ${RSGDLL_E2E_ENTRYPOINT}
        target: /home/steam/rsgdll-entrypoint.sh
        read_only: true
      - type: bind
        source: ${E2E_ARTIFACT_DIR}
        target: /e2e-artifacts
