[package]
name = "rsgdll"
version.workspace = true
edition.workspace = true

[features]
default = []
engine = []
sigscan = []
detour = ["sigscan"]
hook = ["sigscan", "detour"]
async = ["dep:rsgdll-async"]
serde = ["rsgdll-lua/serde"]
backtrace = ["rsgdll-module/backtrace"]
raw = []
full = ["engine", "hook", "async", "serde", "backtrace"]

[dependencies]
rsgdll-lua.workspace = true
rsgdll-macros.workspace = true
rsgdll-module.workspace = true
rsgdll-runtime.workspace = true
rsgdll-async = { workspace = true, optional = true }

[dev-dependencies]
static_assertions = "1"
