[package]
name = "rsgdll"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Framework for Garry's Mod binary Lua modules"
license.workspace = true
readme = "../../README.md"

[features]
default = []
engine = ["dep:rsgdll-engine"]
sigscan = ["dep:rsgdll-sigscan"]
detour = ["sigscan", "dep:rsgdll-detour"]
hook = ["sigscan", "detour"]
async = ["dep:rsgdll-async"]
serde = ["rsgdll-lua/serde"]
backtrace = ["rsgdll-module/backtrace"]
raw = []
full = ["engine", "hook", "async", "serde", "backtrace"]

[dependencies]
rsgdll-lua.workspace = true
rsgdll-macros.workspace = true
rsgdll-module.workspace = true
rsgdll-runtime.workspace = true
rsgdll-async = { workspace = true, optional = true }
rsgdll-engine = { workspace = true, optional = true }
rsgdll-sigscan = { workspace = true, optional = true }
rsgdll-detour = { workspace = true, optional = true }

[dev-dependencies]
static_assertions = "1"
